# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=b'photos/no-img.png', upload_to=b'photos'),
        ),
    ]
